

http://dati.istat.it/index.aspx?queryid=16497
```{r}
library(MASS)
library(cluster)
library(corrplot)
tabellaOriginale=read.csv("C:/Users/HP/OneDrive - University of Pisa/Desktop/STATISTICA/Prima Relazione/prova2020k.csv",header = TRUE)

tabellaOriginale = tabellaOriginale[-c(1),]
tabellaOsservata = data.frame(scale(tabellaOriginale[,-c(1)]))

parcoord(tabellaOsservata)
```

```{r}
wss=rep(0,10)
for(k in 2:10){
  wss[k]=kmeans(tabellaOsservata,k,nstart=30)$tot.withinss
}
plot(2:10,wss[2:10],type="b",ylab = "withinss",pch=20)
```


```{r}
as=rep(0,10)
for(k in 2:10){
  cl=kmeans(tabellaOsservata,k,nstart=30)$cluster
  as[k]=mean(silhouette(cl,dist(tabellaOsservata))[,3])
}
plot(2:10,as[2:10],type="b",ylab = "silhouette",pch=20)
```


```{r}
layout(matrix(1:4,2,2))
plot(silhouette(kmeans(tabellaOsservata,2,nstart=30)$cluster,dist(tabellaOsservata)),main = "2 Cluster")
plot(silhouette(kmeans(tabellaOsservata,3,nstart=30)$cluster,dist(tabellaOsservata)),main = "3 Cluster")
plot(silhouette(kmeans(tabellaOsservata,4,nstart=30)$cluster,dist(tabellaOsservata)),main = "4 Cluster")
plot(silhouette(kmeans(tabellaOsservata,5,nstart=30)$cluster,dist(tabellaOsservata)),main = "5 Cluster")
layout(1)
```


```{r}
k=4
rownames(tabellaOriginale) <- tabellaOriginale$territorio
tabellaOsservata.km=kmeans(tabellaOsservata,k,nstart=30)
tabellaOsservata.pca=princomp(tabellaOsservata)
plot(tabellaOsservata.pca$scores,col=1+tabellaOsservata.km$cluster,ylim=c(-2,6.6),pch=20)
points(predict(tabellaOsservata.pca,tabellaOsservata.km$centers),col=2:(k+1),pch=19)
text(tabellaOsservata.pca$scores,labels=(as.character(rownames(tabellaOriginale))),col=1+tabellaOsservata.km$cluster,pos=3)
```


```{r}

k=3
tabellaOsservata.km=kmeans(tabellaOsservata,k,nstart=30)
tabellaOsservata.pca=princomp(tabellaOsservata)
plot(tabellaOsservata.pca$scores[,c(1,2)],ylim=c(-2,6.6),col=1+tabellaOsservata.km$cluster,pch=20)
points(predict(tabellaOsservata.pca,tabellaOsservata.km$centers),col=2:(k+1),pch=19)
text(tabellaOsservata.pca$scores[,c(1,2)],labels=as.character(row.names(tabellaOriginale)),col=1+tabellaOsservata.km$cluster,pos=3)

```


```{r}
d<-dist(tabellaOsservata)
tabellaOsservata.hc=hclust(d)
plot(ir.hc,hang=-1,cex=0.3)

```

```{r}
tabellaOsservata.hc=hclust(d) # complete linkage
#tabellaOsservata.hc=hclust(d,method="single") # single linkage
#tabellaOsservata.hc=hclust(d,method="average") # average linkage
as=matrix(ncol=2,nrow=10)
for(i in 2:10){
  tabellaOsservata.cut=cutree(tabellaOsservata.hc,i)
  as[i,1]=mean(silhouette(tabellaOsservata.cut,d)[,3])
  as[i,2]=sd(silhouette(tabellaOsservata.cut,d)[,3])
}
as2=as[2:10,]
ymin=min(as2[,1]- as2[,2])
ymax=max(as2[,1] + as2[,2])
plot(2:10,as2[,1],ylab = "silhouette",type="b",pch=20,ylim=c(ymin,ymax))
segments(2:10,as2[,1]-as2[,2],2:10,as2[,1]+as2[,2])

tabellaOsservata.cut=cutree(tabellaOsservata.hc,3)
plot(silhouette(tabellaOsservata.cut,d),col=heat.colors(3),border=par("fg"),main = "silhouette for Complete linkage")
```
```{r}
k=3
tabellaOsservata.pca=princomp(tabellaOsservata)
plot(tabellaOsservata.pca$scores[,c(1,2)],ylim=c(-2,6.6),col=1+tabellaOsservata.cut,pch=20)
#points(predict(tabellaOsservata.pca,tabellaOsservata.cut),col=2:(k+1),pch=19)
text(tabellaOsservata.pca$scores[,c(1,2)],labels=as.character(row.names(tabellaOriginale)),col=1+tabellaOsservata.km$cluster,pos=3)
```


```{r}
biplot(tabellaOsservata.pca,choices=c(1,3),col=c("white","red"))
```



```{r}
c=rep(0,10)
for(i in 2:10){
  c[i]=pam(tabellaOsservata,i)$silinfo$avg.width
}
plot(2:10,c[2:10],type="b",pch=19)

```

```{r}
k=3
tabellaOsservata.km=kmeans(tabellaOsservata,k,nstart=30)
parcoord(tabellaOsservata[,3:13],col=tabellaOsservata.km$cluster)
```

```{r}
tabellaOsservata.loadings=loadings(tabellaOsservata.pca)
tabellaOsservata.rot=varimax(tabellaOsservata.loadings[,1:4])$loadings
corrplot(tabellaOsservata.rot, is.corr=FALSE,method="color", addCoef.col = "black",  number.digits=2, number.cex=0.8)

```

```{r}
```


```{r}
```


```{r}
```

